// Hình vẽ của game. Không phụ thuộc game: chữ, luật, dữ liệu đều do bên dùng truyền vào.
// brush/noise/palette: bút lông vẽ ra canvas (cảnh WebGL lẫn giao diện). chrome: da giao diện 9 mảnh; emblems: huy hiệu, icon tab;
// actions: icon thao tác nét bút. Icon, Portrait: component HTML (mọi hình đều vẽ tay).
export { default as Icon, type Name as IconName } from './Icon.svelte'
export { default as Portrait } from './Portrait.svelte'
export * from './brush'
export * from './noise'
export * from './palette'
export * from './paper'
export * from './landscape'
export * from './buildings'
export * from './fx'
export * from './ui'
export * from './figures'
export * from './icons'
export * from './goods'
export * from './img'
export * from './decor'
export * from './chrome'
export * from './emblems'
export * from './actions'
export * from './world'
